import{a as h,S as b,i as d}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const L="https://pixabay.com/api/?per_page=15";async function f(s,t=1){const a={key:"49367974-1ddb9c95ea8d865fcbee88608",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t};try{return(await h.get(L,{params:a})).data}catch(r){console.log("Помилка при отриманні даних:",r)}}function g(s){const t=document.querySelector(".gallery");document.querySelector(".load-btn"),t.innerHTML="";const a=s.map(e=>`<li class="gallery-item">
    <a class="gallery-link" href=${e.largeImageURL}>
        <img class="gallery-image" src=${e.webformatURL} alt=${e.tags} />
    </a>
    <div class="info">
        <p class="gallery-info">Likes: <span class="galery-info-span">${e.likes}</span></p>
        <p class="gallery-info">Views: <span class="galery-info-span">${e.views}</span></p>
        <p class="gallery-info">Comments: <span class="galery-info-span">${e.comments}</span></p>
        <p class="gallery-info">Downloads: <span class="galery-info-span">${e.downloads}</span></p>
    </div>
</li>`).join("");t.insertAdjacentHTML("beforeend",a),new b(".gallery a").refresh()}const n=document.querySelector(".loader"),m=document.querySelector(".form"),p=document.querySelector("input"),w=document.querySelector(".gallery"),i=document.querySelector(".load-btn");let y=null,l=1,u=0;m.addEventListener("submit",v);i.addEventListener("click",S);async function v(s){if(s.preventDefault(),p.value.trim()==="")return d.show({message:"❌ Eter a search word",position:"topRight",color:"red"});w.innerHTML="",n.style.display="block",y=p.value,l=1;try{const t=await f(y,l);u=t.totalHits,t.hits.length===0?d.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"}):(g(t.hits),i.classList.remove("visually-hidden"),u>15&&(i.style.display="block"))}catch(t){console.log("Помилка при отриманні даних:",t)}finally{n.style.display="none"}m.reset()}async function S(){l+=1,n.style.display="block",n.style.top="100%";try{const s=await f(y,l);g(s.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}l*15>=u?(i.style.display="none",d.show({message:"❌ We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):i.style.display="block"}catch(s){console.log("Помилка при отриманні даних:",s)}finally{n.style.display="none"}}
//# sourceMappingURL=index.js.map
